### PR TITLE
feat: replace node info querier with new GRPC client

### PR DESCRIPTION
**Pull request by RiccardoM**
## Description

This PR replaces the REST call to the `/node_info` endpoint with the new gRPC client instead, providing forward compatibility to all new Cosmos SDK versions after `v0.45`. 

Closes: #73

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit tests.
- [x] Run `make format`.
- [ ] Run `make lint`.
- [ ] Updated the documentation.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [ ] Re-reviewed `Files changed` in the Github PR explorer and added meaningful comments.

### CODE REVIEW

**Comment by RiccardoM** [comment]
@kjawadDeveloper Can you please try this code and let me know if it works? I've made the proper tests but would like a double check just in case

**Comment by kjawadDeveloper** [comment]
@RiccardoM  sure.

**Comment by kjawadDeveloper** [comment]
@RiccardoM  instead of getting the chain id from node or from remote service what if we send this as a parameter. This will increase transaction signing speed.

**Comment by RiccardoM** [comment]
> @RiccardoM instead of getting the chain id from node or from remote service what if we send this as a parameter. This will increase transaction signing speed.

Even though it might work, it wouldn't be that beneficial. Performing the query with a gRPC client only takes a couple of milliseconds, and requiring the developers to know the chain id before-hand it's just an additional hassle with no real benefit. All other libraries do not require this (CosmJS, the Cosmos CLI, etc). I think it's better to provide an easier UX for developers rather than a 200ms faster code.

**Pull request merged**
